module.exports = places = [
  {
    title: "Eiffel Tower",
    description: "Iconic wrought-iron lattice tower in Paris.",
    price: 30,
    location: "Paris",
    country: "France",
    image: "https://example.com/eiffel_tower.jpg",
  },
  {
    title: "Great Wall of China",
    description: "Ancient wall stretching over 13,000 miles.",
    price: 45,
    location: "Beijing",
    country: "China",
    image: "https://example.com/great_wall.jpg",
  },
  {
    title: "Taj Mahal",
    description: "Magnificent white marble mausoleum.",
    price: 25,
    location: "Agra",
    country: "India",
    image: "https://example.com/taj_mahal.jpg",
  },
  {
    title: "Statue of Liberty",
    description: "Symbol of freedom and democracy.",
    price: 20,
    location: "New York",
    country: "USA",
    image: "https://example.com/statue_of_liberty.jpg",
  },
  {
    title: "Colosseum",
    description: "Ancient Roman gladiatorial arena.",
    price: 40,
    location: "Rome",
    country: "Italy",
    image: "https://example.com/colosseum.jpg",
  },
  {
    title: "Machu Picchu",
    description: "Incan citadel set high in the Andes Mountains.",
    price: 50,
    location: "Cusco",
    country: "Peru",
    image: "https://example.com/machu_picchu.jpg",
  },
  {
    title: "Sydney Opera House",
    description: "World-famous performing arts center.",
    price: 35,
    location: "Sydney",
    country: "Australia",
    image: "https://example.com/sydney_opera_house.jpg",
  },
  {
    title: "Christ the Redeemer",
    description: "Iconic statue overlooking Rio de Janeiro.",
    price: 15,
    location: "Rio de Janeiro",
    country: "Brazil",
    image: "https://example.com/christ_the_redeemer.jpg",
  },
  {
    title: "Santorini",
    description: "Beautiful island known for its white-washed buildings.",
    price: 60,
    location: "Santorini",
    country: "Greece",
    image: "https://example.com/santorini.jpg",
  },
  {
    title: "Grand Canyon",
    description: "Vast, scenic canyon carved by the Colorado River.",
    price: 20,
    location: "Arizona",
    country: "USA",
    image: "https://example.com/grand_canyon.jpg",
  },
  {
    title: "Stonehenge",
    description: "Prehistoric monument of standing stones.",
    price: 10,
    location: "Wiltshire",
    country: "England",
    image: "https://example.com/stonehenge.jpg",
  },
  {
    title: "Niagara Falls",
    description: "Massive waterfalls straddling the US-Canada border.",
    price: 25,
    location: "Ontario",
    country: "Canada",
    image: "https://example.com/niagara_falls.jpg",
  },
  {
    title: "Petra",
    description: "Ancient city carved into rock.",
    price: 30,
    location: "Ma'an",
    country: "Jordan",
    image: "https://example.com/petra.jpg",
  },
  {
    title: "Mount Fuji",
    description: "Japan's highest and most famous mountain.",
    price: 40,
    location: "Honshu",
    country: "Japan",
    image: "https://example.com/mount_fuji.jpg",
  },
  {
    title: "Pyramids of Giza",
    description: "Ancient pyramids and the Sphinx.",
    price: 35,
    location: "Giza",
    country: "Egypt",
    image: "https://example.com/pyramids_of_giza.jpg",
  },
  {
    title: "Angkor Wat",
    description: "Large temple complex in Cambodia.",
    price: 25,
    location: "Siem Reap",
    country: "Cambodia",
    image: "https://example.com/angkor_wat.jpg",
  },
  {
    title: "Burj Khalifa",
    description: "Tallest building in the world.",
    price: 75,
    location: "Dubai",
    country: "UAE",
    image: "https://example.com/burj_khalifa.jpg",
  },
  {
    title: "Banff National Park",
    description: "Stunning national park in the Canadian Rockies.",
    price: 20,
    location: "Alberta",
    country: "Canada",
    image: "https://example.com/banff.jpg",
  },
  {
    title: "Table Mountain",
    description: "Flat-topped mountain overlooking Cape Town.",
    price: 15,
    location: "Cape Town",
    country: "South Africa",
    image: "https://example.com/table_mountain.jpg",
  },
  {
    title: "Hagia Sophia",
    description: "Historic mosque and museum in Istanbul.",
    price: 25,
    location: "Istanbul",
    country: "Turkey",
    image: "https://example.com/hagia_sophia.jpg",
  },
];
